name: Deploy Static Website to S3 with CloudFront

on:
  push:
    branches:
      - main  # deploy only on main branch

# env:
#   # Setting an environment variable with the value of a configuration variable
#   env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}  

      # Step 3: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://${{ vars.S3_BUCKET_NAME }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"

    #   # Step 4: Invalidate CloudFront cache
    #   - name: Invalidate CloudFront
    #     run: |
    #       aws cloudfront create-invalidation \
    #         --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
    #         --paths "/*"
